attempt at better error handling

diff --git a/scripts/actual_autograder b/scripts/actual_autograder
--- a/scripts/actual_autograder
+++ b/scripts/actual_autograder
@@ -4,59 +4,86 @@ set -ex
 
 cd /autograder
 
+LEANFILES=$(ls -l submission/*.lean | egrep -c '^-')
+TEXFILES=$(ls -l submission/*.tex | egrep -c '^-')
+
 # We're expecting students to submit two files, a .tex file and a .lean file, but the two autograders
 # expect the submission dir to contain either one or the other. So we split them out to start.
-mkdir lean_submission
-mv submission/*.lean lean_submission/
 
-mkdir tex_submission
-mv submission/*.tex tex_submission/
+if [ $LEANFILES == 1 ]; then 
 
-rm -rf submission
+  mkdir lean_submission
+  mv submission/*.lean lean_submission/
 
-mv source main_source
+fi
+  
+if [ $TEXFILES == 1 ]; then 
+
+  mkdir tex_submission
+  mv submission/*.tex tex_submission/
+
+  rm -rf submission
+
+  mv source main_source
+
+fi
+
 
 #########################################
 ##  LEAN AUTOGRADER EXECUTION
 #########################################
 
-mv lean_submission submission
-mv lean_ag_src source
-cd source
+if [ $LEANFILES == 1 ]; then 
 
-git pull
 
-# The following line is needed for this reason:
-# we have just pulled a new version of the course project,
-# which has the autograder as a dependency.
-# If we update the version of the autograder in that project,
-# `run_autograder_main` may change.
-# So we need to make sure that the latest versions of the dependencies are present
-# before we copy that file over.
+    mv lean_submission submission
+    mv lean_ag_src source
+    cd source
 
-~/.elan/bin/lake update
+    git pull
 
-./lake-packages/autograder/run_autograder_main
+    # The following line is needed for this reason:
+    # we have just pulled a new version of the course project,
+    # which has the autograder as a dependency.
+    # If we update the version of the autograder in that project,
+    # `run_autograder_main` may change.
+    # So we need to make sure that the latest versions of the dependencies are present
+    # before we copy that file over.
 
-cd ..
+    ~/.elan/bin/lake update
 
-# results.json should now contain lean results, now need to append tex results
+    ./lake-packages/autograder/run_autograder_main
+
+    cd ..
+
+
+    # results.json should now contain lean results, now need to append tex results
+
+    mv results/results.json lean_results.json
+
+
+    mv submission lean_submission
+
+fi
 
 #########################################
 ##  TEX AUTOGRADER EXECUTION
 #########################################
 
-mv results/results.json lean_results.json
 
-mv submission lean_submission
-mv tex_submission submission
 
-mv source lean_ag_src
-mv unified_ag_src source
+if [ $TEXFILES == 1 ]; then 
 
-# The OR is so that a compilation failure doesn't ruin the whole autograding script.
-./source/scripts/grade_tex || true
+    mv tex_submission submission
 
-mv results/results.json tex_results.json
+    mv source lean_ag_src
+    mv unified_ag_src source
+
+    # The OR is so that a compilation failure doesn't ruin the whole autograding script.
+    ./source/scripts/grade_tex || true
+
+    mv results/results.json tex_results.json
+
+fi
 
 python3 source/scripts/combine_json.py
